### ISSUE TITLE
Entity Render Error (?)

### ISSUE THREAD

**Issue by ghost** [WenXin20/Warp-Pipes#2]
bowser what???
![image](https://github.com/WenXin20/Warp-Pipes/assets/73998874/7ed87660-56b3-4c6d-994d-57d4857fe343)

**Comment by ghost** [comment]
![image](https://github.com/WenXin20/Warp-Pipes/assets/73998874/4d729233-b9b3-4d3a-bad6-da8fc6c43e5f)

**Comment by WenXin20** [comment]
This is not a bug as discussed in discord. 
This mod doesn't add mobs.
