### ISSUE TITLE
Wrench nerf: reduce attack damage to 1, and remove the sweeping effect

### ISSUE THREAD

**Issue by Jous4n** [WenXin20/Warp-Pipes#4]
I just think the Wrench is a bit too powerful. The damage is too high for how fast it is. Including also that it has the same sweeping effect Swords have, making it completely a weapon. Probably just reducing the attack damage (from 5 to 1) and removing the sweeping effect would balance it just fine.

**Comment by WenXin20** [comment]
That's a good point, I'll look into it

**Comment by WenXin20** [comment]
Attack damage & speed has been reduced and removed the sweeping effect in the newest version.

**Comment by Jous4n** [comment]
Awesome! Thank you so much!
0.8 Attack Speed is perfect.
