### ISSUE TITLE
Endermen + water warp pipe crashes

### ISSUE THREAD

**Issue by usernamepassword123** [WenXin20/Warp-Pipes#5]
A crash occurs after an enderman enters a warp pipe with the flowing water enabled. [Here is the link to the crash log.](https://pastebin.com/vmcEQAzU)

**Comment by WenXin20** [comment]
Thanks, I'll take a look

**Comment by WenXin20** [comment]
Fix has been uploaded! Look for v2.2.3

**Comment by usernamepassword123** [comment]
Thanks for the fix! With my enderman farm being so buggy this was a really annoying bug, lol

**Comment by WenXin20** [comment]
No problem!
